appName = "go-chat"

[mySql]
hostnport = "mysql8"
name = "go-chat"
password = "testing123"
tablePrefix = ""
user = "testing123"

[log]
path = "logs/chat.log"

[msgChannelType]
channelType = "gochannel"

kafkaHosts = "kafka:29092"
kafkaTopic = "go-chat-message"

[Token]
AccessTokenPrivateKey=""
AccessTokenPublicKey=""
AccessTokenExpiresIn="1h"
AccessTokenMaxAge=60