name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: 'create env file'
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          DATABASE: ${{ secrets.DATABASE }}
          CHANNEL_TYPE: ${{ secrets.CHANNEL_TYPE }}
          KAFKA_HOST: ${{ secrets.KAFKA_TOPIC }}
          ACCESS_TOKEN_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}
          ACCESS_TOKEN_PUBLIC_KEY: ${{ secrets.ACCESS_TOKEN_PUBLIC_KEY }}
          ACCESS_TOKEN_EXPIRED_IN: ${{ secrets.ACCESS_TOKEN_EXPIRED_IN }}
          ACCESS_TOKEN_MAXAGE: ${{ secrets.ACCESS_TOKEN_MAXAGE }}
          BUCKET: ${{ secrets.BUCKET }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          URL: ${{ secrets.URL }}
          DEFAULT_USER_AVATAR: ${{ secrets.DEFAULT_USER_AVATAR }}
          DEFAULT_GROUP_AVATAR: ${{ secrets.DEFAULT_GROUP_AVATAR }}
        run: |
          cat <<EOF > .env
          MONGODB_URL="$MONGODB_URL"
          DATABASE="$DATABASE"
          CHANNEL_TYPE="$CHANNEL_TYPE"
          KAFKA_HOST="$KAFKA_HOST"
          ACCESS_TOKEN_PRIVATE_KEY="$ACCESS_TOKEN_PRIVATE_KEY"
          ACCESS_TOKEN_PUBLIC_KEY = "$ACCESS_TOKEN_PUBLIC_KEY"
          ACCESS_TOKEN_EXPIRED_IN = "$ACCESS_TOKEN_EXPIRED_IN"
          ACCESS_TOKEN_MAXAGE = "$ACCESS_TOKEN_MAXAGE"
          BUCKET = "$BUCKET"
          PROJECT_ID = "$PROJECT_ID"
          URL = "$URL"
          DEFAULT_USER_AVATAR = "$DEFAULT_USER_AVATAR"
          DEFAULT_GROUP_AVATAR = "$DEFAULT_GROUP_AVATAR"
          EOF

          echo "cat .env"
          cat .env
          ls -a
      - name: 'create json file'
        env:
          DATA: ${{secrets.GOOGLE_SERVICES_JSON}}
        run: |
          cat keys.json | base64
          echo $DATA > keys.json
          echo "cat keys.json"
          cat keys.json
          ls -a
      - run: flyctl deploy --remote-only
